# Predicting survival on the Titanic

In [1]:
import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

#Load the dataset 
test_data = pd.read_csv("test.csv")
train_data = pd.read_csv("train.csv")

## Preprocessing Testing Data

In [2]:
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [3]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
#test_data.isnull().sum()
    #Age 86 Missing Values 
test_fill_in = train_data['Age'].mean()
test_data['Age'] = test_data['Age'].fillna(test_fill_in)

#filling nan in Fare with the median
test_fill_in_fare = train_data['Fare'].median()
test_data['Fare'] = test_data['Fare'].fillna(test_fill_in_fare)

#Dropping unecessary columns + handling missing values 
test_cleaned = test_data.drop(['Name', 'Cabin', 'Embarked', 'Ticket', 'PassengerId'] , axis = 1, errors = 'ignore')

In [5]:
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

## Preprocessing Training Data

In [6]:
#Dropping unecessary columns + handling missing values 
train_data.drop(['Name', 'Cabin', 'Embarked', 'Ticket','PassengerId'] , axis = 1,inplace = True, errors = 'ignore')
#train_data.isnull().sum()
    #Age has 177 Missing Value 
train_fill_in = test_data['Age'].mean()
train_data['Age'] = train_data['Age'].fillna(train_fill_in)

In [7]:
train_data.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

## Building the Models

In [8]:
#Binary Classification Model Implementation
#Referencing: MN Lab 4 Neural Network Implementation 

#One Hot Encode Categorical Variable --> Map 
train_data['Sex'] = train_data['Sex'].map({'male': 0, 'female': 1})
test_cleaned['Sex'] = test_cleaned['Sex'].map({'male': 0, 'female': 1})

#splitting into x(features) and y(target) + training and testing sets
X = train_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']] #every col but 'survived'
y = train_data ['Survived']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33 ,random_state=42) #42 because that's what we use in class

In [10]:
#fitting the model and evaluating
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)


#prediction on test set
test_pred = rf.predict(test_cleaned)
#final output
Survived = pd.DataFrame({ 
'PassengerId': test_data['PassengerId'],
'Survived': test_pred })
print(Survived)

0.8135593220338984
     PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]